import AdminNav from "@/components/AdminNav/AdminNav";
import "../../globals.css";
import { Inter } from "next/font/google";


export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

const inter = Inter({
  subsets: ["latin"],
  display: "swap",
});

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en" className={inter.className}>
      <body>
        <main>
        <AdminNav />
          <div className="pageWrapper">
            
            <div className="contentWrapper">{children}</div>
            
          </div>
        </main>
      </body>
    </html>
  );
}
