import "./globals.css";
import { Inter } from "next/font/google";
import Nav from "@/components/Nav/Nav";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

const inter = Inter({
  subsets: ["latin"],
  display: "swap",
});

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en" className={inter.className}>
      <body>
        <main>
          <Nav />
          <div className="pageWrapper">
            <div className="leftBox"></div>
            <div className="contentWrapper">{children}</div>
            <div className="rightBox"></div>
          </div>
        </main>
      </body>
    </html>
  );
}
